- name: Create a File
  hosts: all
  gather_facts: false
  vars_files:
    - vars/my_vars.yml

  tasks:
    - name: Create the /u/ibmuser/files directory
      ansible.builtin.file:
        path: /u/ibmuser/files
        state: directory
        mode: '0755'

    - name: Touch a file in the /u/ibmuser/files directory
      ansible.builtin.file:
        path: /u/ibmuser/files/{{ filename }}
        state: touch
        mode: '0644'
